
models:
  - name: stg_lead_source_1
    description: "Raw lead data from source 1"
    columns: 
      - name: company
        description: "The operator of the provider"
        tests:
          - unique
          - not_null
      - name: first_name
        description: "the standardized first name of contacts"
        tests: 
          - not_null
      - name: last_name
        description: "the standardized last name of contacts"
        tests: 
          - not_null
  - name: int_unified_source_leads
    description: "Combine leads from all sources"
    columns:
      - name: first_name
        description: "the standardized first name of contacts"
        tests: 
          - generic_not_null
