
models:
  - name: stg_lead_source_1
    description: "Raw lead data from source 1"
    columns: 
      - name: company
        description: "The operator of the provider"
        tests:
          - unique
          - not_null
      - name: first_name
        description: "Contact's first name"
        tests: 
          - not_null
      - name: last_name
        description: "Contact's last name"
        tests: 
          - not_null
  - name: int_unified_source_leads
    description: "Combine leads from all sources"
    columns:
      - name: phone
        description: "Operator name"
        tests: 
          - generic_not_null
