SELECT 
    CAST(ID AS NVARCHAR(50)) AS ID,
	CAST(CAT AS NVARCHAR(50)) AS CAT,
	CAST(SUBCAT AS NVARCHAR(50)) AS SUBCAT,
	CAST(MAINTENANCE AS NVARCHAR(50)) AS MAINTENANCE

FROM {{ source('dev_crm_erp_database', 'raw_erp_px_cat_g1v2') }} 