# .github/workflows/run-dbt-prod.yml
name: run_dbt_workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # schedule:
  #   - cron: '0 8 * * *'

env:
  DBT_PROFILES_DIR: ./crm_leads_analytics
  DBT_PROJECT_DIR: ./crm_leads_analytics

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      
      - name: Set up DBT Environment
        run: |
          export DBT_PROFILES_DIR=./crm_leads_analytics
          export DBT_PROJECT_DIR=./crm_leads_analytics

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install dbt  # Ensure dbt is installed if not in requirements.txt
    
      - name: Run dbt workflow
        run: |
          dbt debug
          dbt compile --target prod
          dbt run --target prod
    
      - name: Test dbt Prod
        run: |
          dbt test --target prod