# .github/workflows/run-dbt-prod.yml
name: run_dbt_workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # schedule:
  #   - cron: '0 8 * * *'

env:
  DBT_PROFILES_DIR: ${{ github.workspace }}/crm_leads_analytics
  DBT_PROJECT_DIR: ${{ github.workspace }}/crm_leads_analytics

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install dbt-core dbt-snowflake # Ensure dbt is installed if not in requirements.txt

      - name: List Directory Structure
        run: ls -R
        
      - name: Run DBT Debug
        working-directory: ./crm_leads_analytics
        run: dbt debug
          
      - name: Run DBT Compile
        working-directory: ./crm_leads_analytics
        run: dbt compile --target prod
          
      - name: Run DBT
        working-directory: ./crm_leads_analytics
        run: dbt run --target prod
    
      - name: Test dbt Prod
        working-directory: ./crm_leads_analytics
        run: dbt test --target prod